apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: elastic-apm-demo
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  ENVIRONMENT: "kubernetes"
  ORDER_SERVICE_URL: "http://order-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service:8082"
  PAYMENT_FAILURE_RATE: "0"
  INVENTORY_SLOW_MS: "0"
